"""Emit docs/CORPUS-REVIEW.md: every curated row with its source, for review.

The raw wiki pages live in data/raw/, which is gitignored, so this is the
reviewable artifact that travels with the repo. It carries structured fields and
the source reference, never wiki prose.
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dcc_pipeline.validate import read_tables  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "CORPUS-REVIEW.md"
WIKI = "https://dungeon-crawler-carl.fandom.com/wiki/"

FLOOR_NAME = {0: "Before the dungeon", 1: "Floor 1", 2: "Floor 2", 3: "Floor 3"}


def link(source: str) -> str:
    if source.startswith("wiki:"):
        page = source[5:]
        return f"[{page.replace('_', ' ')}]({WIKI}{page})"
    return f"`{source}`"


def main() -> int:
    rows = read_tables()
    lines: list[str] = []
    add = lines.append

    add("# Corpus review\n")
    add("Every curated row with its source, so each claim can be checked against the")
    add("page it came from. Generated by `npm run data:review`; edit the CSVs in")
    add("`data/curated/`, not this file.\n")
    add("Confidence describes the annotation, not the story. `inferred` rows are")
    add("excluded from headline numbers and counted separately in the Ledger.\n")

    counts = Counter()
    for table in ("entities", "facts", "mechanics", "edges", "holdings", "stats"):
        for row in rows[table]:
            if "confidence" in row:
                counts[row["confidence"]] += 1
    total = sum(counts.values())
    add("## Where the corpus stands\n")
    add(f"| Table | Rows |")
    add("|---|---:|")
    for table in ("entities", "aliases", "facts", "status", "edges", "mechanics", "holdings", "stats"):
        add(f"| {table} | {len(rows[table])} |")
    add("")
    add(f"Of {total} rows carrying a confidence: " + ", ".join(
        f"**{counts[level]}** {level}" for level in ("certain", "probable", "inferred")
    ) + ".\n")

    add("## Priced records\n")
    add("The Ledger rests entirely on this table. Check `effect_scale` hardest: it is")
    add("an estimate with no rubric behind it.\n")
    names = {r["id"]: r["canonical_name"] for r in rows["entities"]}
    add("| Record | Floor | Cost | Amount | Effect | Scale | Confidence | Source |")
    add("|---|---:|---|---|---|---:|---|---|")
    for m in sorted(rows["mechanics"], key=lambda r: (r["introduced_floor"], names.get(r["entity_id"], ""))):
        add(
            f"| {names.get(m['entity_id'], m['entity_id'])} | {m['introduced_floor']} | "
            f"{m['cost_type']} | {m['cost_value'] or '—'} | {m['effect_category']} | "
            f"{m['effect_scale']} | {m['confidence']} | {link(m['source'])} |"
        )
    add("")

    add("## Claims\n")
    add("| Subject | Claim | Reveal | Gloss at | Confidence | Source |")
    add("|---|---|---:|---:|---|---|")
    for f in sorted(rows["facts"], key=lambda r: (int(r["reveal_floor"]), r["id"])):
        gloss = f["significance_floor"] if f["significance_floor"] != f["reveal_floor"] else "—"
        claim = f"{f['predicate'].replace('_', ' ')} {names.get(f['object'], f['object'])}"
        add(
            f"| {names.get(f['subject_id'], f['subject_id'])} | {claim} | "
            f"{f['reveal_floor']} | {gloss} | {f['confidence']} | {link(f['source'])} |"
        )
    add("")

    add("## Entities by floor\n")
    for floor in sorted({int(e["introduced_floor"]) for e in rows["entities"]}):
        here = [e for e in rows["entities"] if int(e["introduced_floor"]) == floor]
        add(f"### {FLOOR_NAME.get(floor, f'Floor {floor}')} ({len(here)})\n")
        for kind in sorted({e["type"] for e in here}):
            named = sorted(e["canonical_name"] for e in here if e["type"] == kind)
            add(f"- **{kind}**: {', '.join(named)}")
        add("")

    add("## Character sheets\n")
    add("Only Carl and Donut have floor-scoped source pages, so only they have sheets.")
    add("Every other character's wiki infobox is current as of book 8.\n")
    add("| Crawler | Floor | Level | STR | INT | CON | DEX | CHA |")
    add("|---|---:|---:|---:|---:|---:|---:|---:|")
    for st in sorted(rows["stats"], key=lambda r: (r["entity_id"], int(r["floor"]))):
        add(
            f"| {names.get(st['entity_id'], st['entity_id'])} | {st['floor']} | {st['level']} | "
            f"{st['str']} | {st['int']} | {st['con']} | {st['dex']} | {st['cha']} |"
        )
    add("")
    held = {}
    for h in rows["holdings"]:
        held.setdefault(h["entity_id"], []).append(h)
    for who, items in sorted(held.items()):
        add(f"**{names.get(who, who)}** holds {len(items)} recorded things: " + ", ".join(
            f"{names.get(i['held_id'], i['held_id'])} (floor {i['reveal_floor']}"
            + (f", lost floor {i['ended_reveal_floor']}" if i["ended_reveal_floor"] else "")
            + ")"
            for i in sorted(items, key=lambda r: names.get(r["held_id"], ""))
        ) + ".\n")

    add("## Status\n")
    add("Only what books 1 and 2 establish. Every death the wiki records for these")
    add("characters is cited to book 3 or later, so no departure appears here. An")
    add("entity with no row renders no status at all, and that absence is not evidence")
    add("of anything.\n")
    add("| Entity | Status | Reveal |")
    add("|---|---|---:|")
    for s in sorted(rows["status"], key=lambda r: (int(r["reveal_floor"]), names.get(r["entity_id"], ""))):
        add(f"| {names.get(s['entity_id'], s['entity_id'])} | {s['status']} | {s['reveal_floor']} |")
    add("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(lines)} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
